# -*- coding: utf-8 -*-
"""Copy of aass

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pODJbmkc5FUxttQ9k5ui7clK09bPyv3Q
"""

import streamlit as st
from PIL import Image
st.title('#TemanTapiMenikah ❤️‍🩹')

st.header('_:red[Unconditional Love from your pretty bride]_')

st.text('Halooo?, Cie Ulang tahun!!!')
st.divider()
st.text('Pasti lagi rebahan deh, atau ngga lagi youtub-an haha')
st.divider()
st.text('Coba tebak ini ulang tahun keberapa bersamaa akuuh?')
st.divider()
st.text('Kedepannya, kita akan segera merayakan ulang tahun bersama tiap Mei dan Oktober loh')
st.divider()
st.text('Mari merayakannya dengan cita rasa masakanku, jangan lupa siapa yg cuci piring? wkwk')


st.text_area('test','''
Tak semua bisa kuungkapkan
Sering kali tak berani dibuatnya
Namun kupercaya kita 'kan bersama

Suatu hari telah kuucapkan
Kata-kata hingga akhirnya kau setuju
Melangkah bersama
Selamanya

tau ngga lagu siapa? clue nya camper van di luar nergeri :p
"siapa sangka hobi bersepeda bisa mempersatukan kita berdua?" wkwkkw
"siapa sangka dunia energi terbarukan dan tak terbarukan dapat bertemu?" wkwkk
"siapa sangka ahli botani dan ahli BMKG 8 tahun yang lalu dapat bekerja sama? wkwk
"siapa sangka fisika menjadi kesamaan ilmu yang kita gunakan saat ini? wkkwk
"siapa sangka nama kita dalam warna bunga yang sama pada mading kelas? wkwkk
dan masih banyak sekali kebetulan-kebetulan yang membawa kita bertemu dan bersatu hingga saat ini
    ''')

image = Image.open('Image/B-kkqjUUUAAYKL9')
image2 = Image.open('Image/WhatsApp Image 2023-05-05 at 1.19.45 AM.jpeg')
image3 = Image.open('Image/WhatsApp Image 2023-05-05 at 1.19.57 AM.jpeg')

st.image(image)
st.image(image2)
st.image(image3)


nama_gambar = {
    'Perpusnas': 'Image/Perpusnas.jpeg',
    'CSW': 'Image/CSW_4.jpeg',
    'Mandiri': 'Image/Mandiri_1.jpeg'
}

CSW_Gambar = {
    'CSW_1': 'Image/CSW_1.jpeg',
    'CSW_2': 'Image/CSW_2.jpeg',
    'CSW_3': 'Image/CSW_3.jpeg',
}

# Membuat selectbox dengan nama-nama gambar
pilihan = st.selectbox('With our moments:', list(nama_gambar.keys()))

# Mengambil gambar dari URL dan menampilkan gambar
st.image(nama_gambar[pilihan], caption=pilihan, use_column_width=True)

# Membuat teks deskripsi berdasarkan gambar yang dipilih
if pilihan == 'Long Distance Relationship':
    teks = 'Saat berada di bawah awan yang sama dengan tempat yang berbeda'
    'Aku selalu berusaha untuk mengerti bagaimana keadaanmu adalah satu hal yang penting,'
    'Berempati dan menghabiskan waktu untuk bercerita tentang hari ini'
    'Memastikan kamu selalu bahagia dalam menjalani hari demi hari saat jarak memisahkan.'
    'Terimkasih jarak, kamu telah mengajarkan kami makna selalu RINDU setiap saat'
    '(Aku telpon ya), (boleh telpon ngga), (lagi dimana)'
    'hahahha kalimat hangat yang harusnya banyak tertulis di ruang obrolan kita'
    'rindu itu unik ya! rindu tidak pernah memberikan kesempatan pada rasa lelah menghilang dengan tidur.'
    'tapi rindu memberikan kesempatan pada rasa lelah menghilang dengan cukup mendengar suaramu'
    'kadang aku membayangkan, bagaimana nasib kita jika tanpa koneksi internet dan smarthphone hahha'
    'kadang aku membayangkan, bagaimana jika doraemon meminjamkan pintunya untuk 1x sehari bisa kemanapun'
    'aku akan membayar doraemon dengan creamy spagetti buatanku agar dia mau meminjamkan pintunya'
    'tentu pintunya akan aku gunakan untuk mengunjungimu hihihihi 😄😄😄😄😄😄😄😄😄'

elif pilihan == 'Long Distance Relationship':

    pilihan = st.selectbox('With our moments:', list(CSW_Gambar.keys()))
    st.image(CSW_Gambar[pilihan], caption=pilihan, use_column_width=True)
    if pilihan == 'Pasuruan, Jawa Timur':
        teks = 'Ditempat ini banyak cerita kita, satu yang teringat adalah ' \
               'kita teman sekelas di SMA yang sama, berawal dari saling mangagumi' \
               'berakhir dengan saling menjaga jarak hingga 2020 '
    elif pilihan == 'Purwokerto - Balikpapan' :
        teks = 'Belum mengerti sebagai seorang wanita dan laki-laki untuk PDKT' \
               'tapi inget banget tiap minggu selalu menyempatkan telepon untuk bermain kuis ' \
               'selalu resah dengan perbedaan waktu 1 jam diantara 2 kota ini ' \
               'berusaha tetap sabar dan mengendalikan diri untuk percaya dan tidak saling cemburu  '
    elif pilihan == 'Semarang - Jakarta' :
        teks = 'Meski tidak sejauh PWT - BPN, tapi rindu semakin membesar di hari demi hari ' \
               'banyak ditinggal tidur tiap sleep call hahaha ' \
               'banyak ditinggal main dan nge gym dateng malem ya? pasti sebel dikit hahha' \
               'tapi bisa naik kereta bareng, meski sekali doang hahaha ' \
               'mana yaaa dulu katanya mau ketemu di tengah-tengah kota (cirebon) sampe sekarang belom terealisasi haha ' \
               'kita lebih sering menghabiskan waktu untuk bertemu 1x sebulan krn jarak yang tidak terlalu jauh ' \
               'wkwkwk ga habis pikir, meski 1x sebulan ketemu kenapa tetep rinduuuuuuu? , ' \
               'wajar deh, kan kamu ngangenin! apalagi aku? setuju? 😂😂😂😂😂😂 '

elif pilihan == 'E-Day':
    teks = 'Aku pernah ingat sempet ngomong : mau lamaran atau nikah pas di hari ulang tahunku' \
           'dan yaaa, kamu mengusahakan itu sampai menjadi kado terindah di ulang tahunku yang ke-25. ' \
           'terimakasih sekali lagi aku ucapkan untuk kado terindah sepanjang 25 tahunku' \
           'mas bener-bener selalu mendengarkan apa yang aku rasakan, bahkan hal kecil sekalipun ' \
           'jangan pernah berubah ya mas.' \
           'aku akan terus berusaha untuk selalu ada dan taat kepada yang mulia suami tercinta (doain ya) ' \
           'tapi rewardnya jangan lupa ya sesuai kesepakatan wkwkkwkw. ' \
           'ih seneng deh godain mas pake kalimat 'torryburch' wkkwkwkwk ' \
           'aku juga seneng pas mas bilang aku cantik kalo pake kerudung buttonscarves, artinya aku boleh beli keruudng lagi hahaha'
st.write(teks)

st.text_area(' ', '''
    Cie senyum senyum sendiri cie...
    sekali lagi, aku ucapkan selamat ulang tahun ya sayang
    tahun ini belom bisa bareng lagi ngerayainnnya
    semoga tahun depan dan tahun tahun berikutnya kita selalu bersama

    cuma tulisan ini yang bisa aku kirim ke mas
    kadonya menyusul deh kalo aku sudah gajian *ups wkkwkwkw
    pokoknya kadonya aku pastikan gaakan pernah bisa dilupain haha

    Mas rizal sayang (kontak di hp ku)
    aku cuma bisa doain yang terbaik untuk kelancaran kehidupan kita kedepannya
    aku tau mas capek banget kerjanya, tapi tetep jaga kesehatan ya mas dengan minum air, dan memenuhi protein harian
    hahhahaha sabar beberapa bulan lagi mas ga kesepian lagii
    aku nyanyikan lagu nina bobo tiap mau tidur *wkwkk

    Maafkan bibi ya mas kalo sering cari gara gara pas mas lagi capek
    mari bekerja sama untuk mewujudkan mimpi mimpi kita kedepannya!
    hurry up! i love u and happy birthday sayang

    Love letter from your bride (to be), and with tears while writing code

    with love,
    Bibi cantik tiada duanyaaaaaa
    ''')

img_1 = Image.open('Image/hihi.jpeg')
img_2 = Image.open('Image/a time called u.jpeg')
img_3 = Image.open('Image/ur my destiny.jpeg')



def handle_upsert():
    st.balloons()
    print('clicked handle_upsert()')

if st.button('hihi' , on_click=handle_upsert(), disabled=True):
    st.image()
elif st.button('a time called u', on_click=handle_upsert()):
    st.image(img_3)
elif st.button('ur my destiny' , on_click=handle_upsert()):
    st.image(img_2)

